### ISSUE TITLE
Snippet-Docstring

### ISSUE THREAD

**Issue by L3MON4D3** [saadparwaiz1/cmp_luasnip#1]
Just FYI, Luasnip now supports docstrings (textual representations) of snippets via `snip:get_docstring()`, could be interesting to display in the documentation, if you'd like to support that :)

**Comment by saadparwaiz1** [comment]
Hey, sounds like a great feature I'd add the support for it as soon as I'm back after vacation :D

**Comment by L3MON4D3** [comment]
Niice, looking forward to it :+1:

**Comment by saadparwaiz1** [comment]
If you can checkout the new commit that'll be great 😁

**Comment by L3MON4D3** [comment]
That was fast :D Lemme check..

**Comment by L3MON4D3** [comment]
Pretty much lgtm apart from the two nitpicks :ok_hand:

**Comment by saadparwaiz1** [comment]
have fixed the the pcall issue in the pull request. let me know what you think about the `vim.bo.filetype` if you are fine with the explanation I'll merge it or else I'll update the pull request with the change and then merge this :)
