### ISSUE TITLE
Feature request: choice node to completion menu.

### ISSUE THREAD

**Issue by uga-rosa** [saadparwaiz1/cmp_luasnip#12]
Is it difficult to give a choice as a completion candidate when you are in a choice node?

**Comment by L3MON4D3** [comment]
You can get a similar effect (see choices) using [this](https://github.com/L3MON4D3/LuaSnip/wiki/Misc#choicenode-popup), not sure if there would be much (any) benefit to having the choices in the regular completion menu.

**Comment by uga-rosa** [comment]
I tried that and that's why I raised this issue.
I was a little confused because it looks similar to the regular completion but operates differently. Since you guys don't seem to find it significant, I'll make an effort to mapping.
