### ISSUE TITLE
Some entries are missing in popupmenu

### ISSUE THREAD

**Issue by xeluxee** [saadparwaiz1/cmp_luasnip#13]
https://github.com/hrsh7th/nvim-cmp/issues/157#issuecomment-920331704 (TLDR when LSP source is active some snippets from LuaSnip source aren't visible in popupmenu)

I thought this was a `nvim-cmp` issue, but @hrsh7th said that this issue is related to LuaSnip source

**Comment by saadparwaiz1** [comment]
Hi yes I'll look into it :)

**Comment by saadparwaiz1** [comment]
I can't reproduce here's the screenshot of both for snippets showing up
![Screenshot 2021-09-16 at 18 41 41](https://user-images.githubusercontent.com/73385353/133659600-a9479168-f446-42be-9712-23a18d923bc9.jpg)

**Comment by saadparwaiz1** [comment]
Here's the minimal config I tried. Can you reproduce with this config?

```lua
vim.cmd [[packadd packer.nvim]]

require('packer').startup(function()
	use 'wbthomason/packer.nvim'
	use {
		'L3MON4D3/LuaSnip',
		requires = {
			'rafamadriz/friendly-snippets'
		}
	}
	use {
		'hrsh7th/nvim-cmp',
		requires = {
			'hrsh7th/cmp-nvim-lsp',
			'saadparwaiz1/cmp_luasnip'
		}
	}

	use {
		'neovim/nvim-lspconfig'
	}
end)

require('luasnip').config.setup({})
require('luasnip.loaders.from_vscode').load()


local cmp = require('cmp')
cmp.setup {
	snippet = {
		expand = function(args)
			require'luasnip'.lsp_expand(args.body)
		end
	},
	sources = {
		{ name = 'luasnip' },
		{ name = 'nvim_lsp'},
	},
	mapping = {
	  ['<C-d>'] = cmp.mapping.scroll_docs(-4),
	  ['<C-f>'] = cmp.mapping.scroll_docs(4),
	  ['<C-Space>'] = cmp.mapping.complete(),
	  ['<C-e>'] = cmp.mapping.close(),
	  ['<CR>'] = cmp.mapping.confirm({
	    behavior = cmp.ConfirmBehavior.Replace,
	    select = true,
	  })
	}
}

local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities = require('cmp_nvim_lsp').update_capabilities(capabilities)

require'lspconfig'.clangd.setup {
  capabilities = capabilities,
}
```

**Comment by xeluxee** [comment]
I tried your minimal config and I can't reproduce this issue with your config
Maybe it's a problem with my config...
I'll investigate and I'll let you know

**Comment by saadparwaiz1** [comment]
@xeluxee sounds good :)

**Comment by xeluxee** [comment]
Just discovered that this issue was caused by `dup` setting in `vim.CompletedItem` variable
I'm trying LunarVim so I didn't know about this setting that was already present there.
Setting `dup` to 1 makes everything fine.

Sorry for wasting time

**Comment by saadparwaiz1** [comment]
Thank you for letting me know :)
