### ISSUE TITLE
JSON snippets with autotrigger not in cmp menu

### ISSUE THREAD

**Issue by lambtho12** [saadparwaiz1/cmp_luasnip#25]
Luasnip's commit [@737a2e7](https://github.com/L3MON4D3/LuaSnip/commit/737a2e7f4a9a0ef215e204393bb33cf3118ca51f) introduced the possibility to specify a "luasnip" field in a snippet JSON file so the snippets can autotrigger.

If that field is set and autotrigger is true, the snippet will not be listed in the nvim-cmp menu. I believe it should show up in the cmp menu, no matter the autotrigger behavior. 

Example snippet config 
```json
  "uuid": {
    "prefix": "UUID",
    "body": [
      "${CURRENT_YEAR}${CURRENT_MONTH}${CURRENT_DATE}${CURRENT_HOUR}${CURRENT_MINUTE}"
    ],
    "description": "UUID",
    "luasnip": {
      "autotrigger": true
    }
  },
```

**Comment by saadparwaiz1** [comment]
Bit hesitant about implementing this just because I think competition menu should only show snippets that have to be triggered manually but I'll create a pull request for this and we can discuss more :)

**Comment by saadparwaiz1** [comment]
you can try out #27  to see if this fixes it for you
