### ISSUE TITLE
Snippet Completion Options disappear

### ISSUE THREAD

**Issue by barrett-ruth** [saadparwaiz1/cmp_luasnip#32]
Consider the following LuaSnip config:
```lua
local ls = require 'luasnip'

ls.config.set_config {
    history = true,
    updateevents = 'TextChanged,TextChangedI',
}

local extras = require 'luasnip.extras'
local fmt = require('luasnip.extras.fmt').fmt
local i = ls.insert_node
local rep = extras.rep
local s = ls.s

ls.snippets = {
    lua = {
        s('lr', fmt("local {} = require '{}'", { i(1), i(2) })),
        s('<', fmt('<{}>{}</{}>', { i(1), i(2), rep(1) })),
        s('</', fmt('<{}/>', { i(1, '') })),
    },
}
```
Replicate: 
1. Typing "lr" in a lua file with nvim-cmp on correctly previews `lr~ Snippet` in the completion dropdown.
2. Typing "<" correctly previews both `<~ Snippet` and `</~ Snippet`
3. However, typing "</" previews a whole load of completion options (snippets for function, do, if, etc.), as if completion was opened on an empty new line, when I believe it should preview the `</~ Snippet` option alone.

Can you replicate this config, and if so, is this the desirable outcome? It seems like it is dismissing the `</` options, perhaps because of the forward slash?

**Comment by saadparwaiz1** [comment]
We don't actually do prefix matching in cmp_luasnip. That's actually handed by nvim-cmp itself. Best to move this bug report to there I think. But I can have a look meanwhile :)

**Comment by barrett-ruth** [comment]
Thanks! 
I didn't know which repo to put it in, but given that cmp actually recognizes the snippet I should've proposed the source was not the problem.

Feel free to close.

**Comment by barrett-ruth** [comment]
Solution: sourcing luasnip config before nvim-cmp config. Silly mistake.
