### ISSUE TITLE
No longer directly access `ls.snippets`

### ISSUE THREAD

**Issue by L3MON4D3** [saadparwaiz1/cmp_luasnip#33]
Hi!

Luasnip is removing direct access to `ls.snippets` (and changing the internal snippet-storage), which means that we'll have to adapt `cmp_luasnip` to no longer store an index into the ft-tables.

It will still be possible to get a list of snippets by filetype, and indices into these would work, but storing a direct reference, in some way, to the snippet would be preferable (imo).
I opened an [issue in `cmp`](https://github.com/hrsh7th/nvim-cmp/issues/851) about just that, not sure if it'll lead to changes in cmp, if it doesn't, we'll implement some `snippet->key`/`key->snippet`-conversion in luasnip.

I'm not sure if it'll be easy to adapt the cache, haven't really thought about it yet, this is more of a FYI :P

**Comment by saadparwaiz1** [comment]
Ah yeah man thanks for the heads up! Worst cache we remove the cache

**Comment by saadparwaiz1** [comment]
@L3MON4D3 should we close this?

**Comment by L3MON4D3** [comment]
Right, yes
