### ISSUE TITLE
attempt to index local 'snip' (a nil value)                                           

### ISSUE THREAD

**Issue by vsedov** [saadparwaiz1/cmp_luasnip#39]
```lua
E5108: Error executing lua ...ite/pack/packer/opt/cmp_luasnip/lua/cmp_luasnip/init.lua:132: attempt to index local 'sn
ip' (a nil value)                                                                                                     
stack traceback:                                                                                                      
        ...ite/pack/packer/opt/cmp_luasnip/lua/cmp_luasnip/init.lua:132: in function 'execute'                        
        ...re/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/source.lua:360: in function 'execute'                        
        ...are/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/entry.lua:439: in function 'execute'                        
        ...hare/nvim/site/pack/packer/opt/nvim-cmp/lua/cmp/core.lua:468: in function <43/168e(25%)/[Loadingkworkspace]
t/nvim-cmp/lua/cmp/core.lua:467>                                                      42/275 (14%) [Loading workspace]
        ...site/pack/packer/opt/nvim-cmp/lua/cmp/utils/feedkeys.lua:51: in function <...site/pack/packer/┌psumneko_lua
lua/cmp/utils/feedkeys.lua:49>
```

Snippets triggers no longer work?  Is this due to new changes to luasnip ? 

Would you like a min config for this ?

**Comment by milkias17** [comment]
I am having the same issue. Seems an update from Luasnip breaks cmp_luasnip.

**Comment by L3MON4D3** [comment]
I don't get this issue, a minimal config would be great👍

**Comment by milkias17** [comment]
Yeah just checked and its not a cmp_luasnip issue sorry about that. Luasnip made breaking changes that changes the way you define snippets. When you define the snippets in the "new" way everything just works.

**Comment by L3MON4D3** [comment]
Oooooh, right, I didn't consider that the deprecation-period isn't officially over :grimacing::grimacing:
My bad, I'll get the Breaking Changes in Luasnip out asap, hopefully everyone sees them while updating.

**Comment by vsedov** [comment]
Yep, its pretty muc how snippets are defined now, :) @milkias17 thanks for clarifying.

**Comment by vsedov** [comment]
> I'm not having this issue, a minimal config would be great+1

do you still need the min config ? or nah, don't think its required now, right ?

**Comment by L3MON4D3** [comment]
> nah, don't think its required now, right ?

Yep, pretty sure that was the problem
