### ISSUE TITLE
Help wanted: Treesitter highlight lost after enabling cmp_luasnip

### ISSUE THREAD

**Issue by stark-zhang** [saadparwaiz1/cmp_luasnip#40]
I met a confused problem after enabling this plugin, the treesitter highlight would be ineffective in the first buffer. But highlight will be restored in next buffers, whatever methods to open them.

Environment:

+ nvim 0.6.1/ 0.7.0 nightly
+ CentOS 7.9

```text
NVIM v0.7.0-dev+1233-gabbc9148d
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by p8zhang@l1sw-env

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/host/workdir/local/share/nvim"

Run :checkhealth for more info
```

Steps to Reproduce:

1. download the file as `miniconf.lua`,
[miniconf.txt](https://github.com/saadparwaiz1/cmp_luasnip/files/8386559/miniconf.txt)

2. install the `packer.nvim`, ignore this step if it has been installed,
2. run `nvim -u miniconf.lua +PackerSync`
3. wait for the completion of process of packer.nvim, then open a lua code, python code or c/cpp code file use `:e <somefile>`,
4. you will found no highlight enabled but highlight group created by treesitter could be found in  output of command `:hi`,
5. open another buffer, you could found the highlight enabled.

**Comment by saadparwaiz1** [comment]
Interesting. I don't seem to having this problem but I'm on 0.6.1 so maybe that's why? Have you tried it with 0.6.1 yet? See if that fixes it if not I'll try and see if I can recreate this

**Comment by stark-zhang** [comment]
yes, I retried with nvim 0.6.1:
![image](https://user-images.githubusercontent.com/17326718/161180607-351fcdf5-3453-4bc6-88c2-1aaee2016f4b.png)

you could find that no highlight enabled but highlight group, such as `TSFunction`, was loaded.

**Comment by saadparwaiz1** [comment]
interesting. have you reported this over to people to nvim-treesitter?

**Comment by stark-zhang** [comment]
I have not reported this to `nvim-treesitter`, because I enabled `nvim-cmp` and many completion source in my configuration and they work well. this problem appears after enabling `cmp_luasnip` and `LuaSnip` only.

you can find my completion configuration [here](https://github.com/stark-zhang/dotfiles-on-unix-like/blob/master/nvim/lua/modules/lsp/init.lua).
