### ISSUE TITLE
Plugin license

### ISSUE THREAD

**Issue by unmatched-paren** [saadparwaiz1/cmp_luasnip#41]
Okay, so it's gonna look really bad on my profile that all I've been doing on github is complain to people about licenses (I use sr.ht instead of github for code hosting, so I don't have any projects here) but... could you please put a license on this plugin? Thanks!

**Comment by saadparwaiz1** [comment]
Hi yes sure! @L3MON4D3 any licenses you prefer?

**Comment by unmatched-paren** [comment]
Thank you (both) for responding so quickly! Honestly there's not really any difference between Apache and (say) the MIT/Expat or BSD-3-clause license other than Apache being way bigger and harder to understand; it apparently has protections against patent treachery, but I don't think you'd be worried about that on a small project like this one :) 

I'd personally just slap an MIT/Expat license on it and be done.

**Comment by saadparwaiz1** [comment]
@unmatched-paren  have added a license now :)

**Comment by unmatched-paren** [comment]
Thank you!
