### ISSUE TITLE
getting this error when autocompleting

### ISSUE THREAD

**Issue by modisek** [saadparwaiz1/cmp_luasnip#42]
![error](https://user-images.githubusercontent.com/4046784/162753938-11ce04fd-7c0d-4963-93b5-6e06438d9910.png)

**Comment by L3MON4D3** [comment]
Is your luasnip up to date?

**Comment by modisek** [comment]
I updated Luasnip..now it says Error running config for LuaSnip module 'config.snippets' not found

**Comment by L3MON4D3** [comment]
Ah, we had some major changes, check here for some tips on adapting: https://github.com/L3MON4D3/LuaSnip/issues/81#issuecomment-1073301357

**Comment by modisek** [comment]
alright thank you

**Comment by saadparwaiz1** [comment]
@L3MON4D3  thanks for the help :D

**Comment by p0da** [comment]
@saadparwaiz1 May want to close this.
