### ISSUE TITLE
Is there any ways to remove `~` in snippet completion window?

### ISSUE THREAD

**Issue by NEX-S** [saadparwaiz1/cmp_luasnip#48]
I'm wondering how to remove `~` in the completion window like `for ~` to `for`, I think the icon already shows us that this item is a snippet, and it's expandable, so `~` in the completion window feels a bit redundant
![Screenshot from 2022-09-02 08-28-31](https://user-images.githubusercontent.com/97107165/188129256-f245210d-fb46-46f0-a357-c9f1d07b4ac2.png)

**Comment by amarakon** [comment]
Why did you close this issue?

**Comment by amarakon** [comment]
You're right, thanks for opening an issue on nvim-cmp.
