### ISSUE TITLE
Neovim freezing when pressing Tab

### ISSUE THREAD

**Issue by DrMondGnu** [saadparwaiz1/cmp_luasnip#53]
### Problem
Neovim freezes when pressing tab or strg-I

### Conditions
Pressing tab or strg-I in normal mode without there being a double-dot ':' put in.

### Info
I tracked the problem down to this function. 
https://github.com/saadparwaiz1/cmp_luasnip/blob/18095520391186d634a0045dacaa346291096566/lua/cmp_luasnip/init.lua#L117
It somehow gets called when pressing tab, but i unfortunately i don't know were it is mapped from, but it should not be a local mapping by me.

**Comment by saadparwaiz1** [comment]
This would be a super-tab like mapping by `nvim-cmp`

**Comment by DrMondGnu** [comment]
> This would be a super-tab like mapping by `nvim-cmp`

Sry for the late response, and could explain what exaclty the super-tab like mapping does? I don't really know the difference between the super-tab and the normal. Also should i modify the mapping to check if there is a double-dot  or modify the function to check for that?

**Comment by DrMondGnu** [comment]
I'm opening another issue with updated info and where i think the problem really lies
