### ISSUE TITLE
Can't install plugin

### ISSUE THREAD

**Issue by DanielTate** [saadparwaiz1/cmp_luasnip#55]
Hey I'm using Packer and I can't seem to install this plguin I get this error:

```
 ✗ Failed to install saadparwaizl/cmp_luasnip
  Errors:
    Cloning into '/home/dan/.local/share/nvim/site/pack/packer/start/cmp_luasnip'...
    fatal: could not read Username for 'https://github.com': terminal prompts disabled
```

Not really sure whats going on here I have my github ssh key set up correctly as about 20 other plugins have no problem installing.

I have been following this tutorial https://www.youtube.com/watch?v=ub0REXjhpmk but fail in installing this plugin.

**Comment by saadparwaiz1** [comment]
I think you have a typo in the repo name it's `saadparwaiz1/cmp_luasnip` not `saadparwaizl/cmp_luasnip`

**Comment by DanielTate** [comment]
Haha! Thanks I should type less!
