### ISSUE TITLE
module 'cmp' not found

### ISSUE THREAD

**Issue by Rohith-JN** [saadparwaiz1/cmp_luasnip#56]
I am getting this error when I try to install `cmp_luasnip`

[Error](https://user-images.githubusercontent.com/78314165/213921685-ec37989e-f4e7-4f27-95bf-b199b0864e7c.png)

Using packer:
```
use({ "L3MON4D3/LuaSnip" })

-- auto-completion engine
use({
    "hrsh7th/nvim-cmp",
    config = [[require('config.nvim-cmp')]],
    after = "lspkind-nvim",
    requires = {
        "saadparwaiz1/cmp_luasnip",
        "hrsh7th/cmp-nvim-lua",
        "hrsh7th/cmp-nvim-lsp",
        "hrsh7th/cmp-path",
        "hrsh7th/cmp-buffer",
        "hrsh7th/cmp-omni",
    },
})

use({ "saadparwaiz1/cmp_luasnip" })

use({
    "hrsh7th/cmp-nvim-lua",
    after = "cmp_luasnip",
})

-- nvim-cmp completion sources
use({ "hrsh7th/cmp-nvim-lsp", after = "nvim-cmp" })
use({ "hrsh7th/cmp-path", after = "nvim-cmp" })
use({ "hrsh7th/cmp-buffer", after = "nvim-cmp" })
use({ "hrsh7th/cmp-omni", after = "nvim-cmp" })
```

Here is my [nvim-config](https://github.com/Rohith-JN/nvim-config)

**Comment by TornaxO7** [comment]
Remove those lines:
```lua
use({ "saadparwaiz1/cmp_luasnip" })

use({
    "hrsh7th/cmp-nvim-lua",
    after = "cmp_luasnip",
})
```

**Comment by Rohith-JN** [comment]
The error persists

**Comment by L3MON4D3** [comment]
Maybe packer needs the full plugin-name in `after`? And/Or the `after`-directive has to be added to `cmp_luasnip` too? Try copy-pasting someone elses setup and see if it works/what changes make it no longer work
(Also, I suspect this is some error with packer, maybe look in their issues)

**Comment by Rohith-JN** [comment]
@L3MON4D3 I tried switching configs and also modified the order of plugins, nothing worked. Maybe it is a packer issue
