### ISSUE TITLE
fatal: could not read Username for 'https://github.com': terminal prompts disabled

### ISSUE THREAD

**Issue by Jimmytheprofessionaldumbass** [saadparwaiz1/cmp_luasnip#63]
Failed (1)                                                                                                ~               ○ cmp_luasnip  nvim-cmp      ■ clone failed                                                            ~                   Cloning into 'C:/Users/Jimmy/AppData/Local/nvim-data/lazy/cmp_luasnip'...                           ~                   fatal: could not read Username for 'https://github.com': terminal prompts disabled                  

Done with lazy.nvim, every other plugin works but jst not this. like I can download the zip from github alright but not using lazy.nvim. Also im going powershell windows

**Comment by saadparwaiz1** [comment]
Issue with lazy.nvim not this plugin. Best bet would be to raise an issue there.
